require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/growth_records", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # GrowthRecord. As you add validations to GrowthRecord, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      GrowthRecord.create! valid_attributes
      get growth_records_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      growth_record = GrowthRecord.create! valid_attributes
      get growth_record_url(growth_record)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_growth_record_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      growth_record = GrowthRecord.create! valid_attributes
      get edit_growth_record_url(growth_record)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new GrowthRecord" do
        expect {
          post growth_records_url, params: { growth_record: valid_attributes }
        }.to change(GrowthRecord, :count).by(1)
      end

      it "redirects to the created growth_record" do
        post growth_records_url, params: { growth_record: valid_attributes }
        expect(response).to redirect_to(growth_record_url(GrowthRecord.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new GrowthRecord" do
        expect {
          post growth_records_url, params: { growth_record: invalid_attributes }
        }.to change(GrowthRecord, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post growth_records_url, params: { growth_record: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested growth_record" do
        growth_record = GrowthRecord.create! valid_attributes
        patch growth_record_url(growth_record), params: { growth_record: new_attributes }
        growth_record.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the growth_record" do
        growth_record = GrowthRecord.create! valid_attributes
        patch growth_record_url(growth_record), params: { growth_record: new_attributes }
        growth_record.reload
        expect(response).to redirect_to(growth_record_url(growth_record))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        growth_record = GrowthRecord.create! valid_attributes
        patch growth_record_url(growth_record), params: { growth_record: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested growth_record" do
      growth_record = GrowthRecord.create! valid_attributes
      expect {
        delete growth_record_url(growth_record)
      }.to change(GrowthRecord, :count).by(-1)
    end

    it "redirects to the growth_records list" do
      growth_record = GrowthRecord.create! valid_attributes
      delete growth_record_url(growth_record)
      expect(response).to redirect_to(growth_records_url)
    end
  end
end
